# Generated by apps/desktop/scripts/homebrew-cask.mjs from the beta release
# manifest. Do not edit by hand — the next promotion overwrites it.
cask "turnpanel" do
  version "26.9.19"
  sha256 "8a313129344774851b3e24af5bfcfac32243d91924d3586e862a13d12641cc9c"

  url "https://alex.research.echo.win/alex/v26.09.19/TurnPanel-#{version}-arm64.zip"
  name "TurnPanel"
  desc "Local-first AI workspace"
  homepage "https://turnpanel.com/"

  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :ventura

  app "TurnPanel.app"

  # The build is ad-hoc signed, not notarized, and Homebrew quarantines what it
  # downloads — without this Gatekeeper blocks the first launch.
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{appdir}}/TurnPanel.app"]
  end

  uninstall quit: "com.electron.turnpanel"

  zap trash: [
    "~/.turnpanel",
    "~/Library/Application Support/TurnPanel",
    "~/Library/Logs/TurnPanel",
    "~/Library/Preferences/com.electron.turnpanel.plist",
    "~/Library/Saved Application State/com.electron.turnpanel.savedState",
  ]
end
