# Generated by apps/desktop/scripts/homebrew-cask.mjs from the beta release
# manifest. Do not edit by hand — the next promotion overwrites it.
cask "turnpanel" do
  version "26.9.21"
  sha256 "d7c46706b828194370c699e8c6d731f13e17a0c5ef51833540b9bc72173449c8"

  url "https://turnpanel.com/download/brew/v26.09.21/TurnPanel-#{version}-arm64.zip"
  name "TurnPanel"
  desc "Local-first AI workspace"
  homepage "https://turnpanel.com/"

  auto_updates true
  depends_on arch: :arm64
  depends_on macos: :ventura

  app "TurnPanel.app"

  # The build is ad-hoc signed, not notarized, and Homebrew quarantines what it
  # downloads — without this Gatekeeper blocks the first launch.
  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{appdir}}/TurnPanel.app"]
  end

  uninstall quit: "com.electron.turnpanel"

  zap trash: [
    "~/.turnpanel",
    "~/Library/Application Support/TurnPanel",
    "~/Library/Logs/TurnPanel",
    "~/Library/Preferences/com.electron.turnpanel.plist",
    "~/Library/Saved Application State/com.electron.turnpanel.savedState",
  ]
end
